"""add user video reactions table

Revision ID: b19c8167a84c
Revises: 0002_v1_tables
Create Date: 2026-01-30 11:30:54.281107
"""

from alembic import op
import sqlalchemy as sa


revision = 'b19c8167a84c'
down_revision = '0002_v1_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_video_reactions',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('video_id', sa.UUID(), nullable=False),
                    sa.Column('reaction_type', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['video_id'], ['videos.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # Add unique constraint to ensure a user can only have one reaction per video
    op.create_unique_constraint('uq_user_video', 'user_video_reactions', [
                                'user_id', 'video_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_video', 'user_video_reactions', type_='unique')
    op.drop_table('user_video_reactions')
    # ### end Alembic commands ###
